on: push
name: deploy
env:
  DEV_CLUSTER_KUBECONF: ${{ secrets.DEV_CLUSTER_KUBECONF }}

jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      
    steps:
    - name: pull kubeconfig
      run: |
        mkdir kubeconf
        echo "$DEV_CLUSTER_KUBECONF" > kubeconf/kubeconf.conf

    - name: envsub kube.conf
      run: |
        cat kubeconf/kubeconf.conf
    
    - uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: get pods
    
    - name: Checkout
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color --auto-approve

