on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: write
      
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true


